<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IP-MTY-AVALOS" failures="1" tests="2" name="com.opensource.admin.qa.TC003_Admin_AddNewUser" time="15.487" errors="0" timestamp="07 Jul 2021 23:15:22 GMT" skipped="1">
  <testcase classname="com.opensource.admin.qa.TC003_Admin_AddNewUser" name="TC001_AdminSearchEmployee_POM_Script" time="0.000">
    <skipped/>
  </testcase> <!-- TC001_AdminSearchEmployee_POM_Script -->
  <testcase classname="com.opensource.admin.qa.TC003_Admin_AddNewUser" name="beforeTest" time="15.487">
    <failure message="JSON file is not found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: JSON file is not found
at org.testng.Assert.fail(Assert.java:96)
at com.opensource.base.SeleniumWrapper.getJSONValue(SeleniumWrapper.java:210)
at com.opensource.admin.qa.TC003_Admin_AddNewUser.beforeTest(TC003_Admin_AddNewUser.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- beforeTest -->
</testsuite> <!-- com.opensource.admin.qa.TC003_Admin_AddNewUser -->
